[package]
name = "admiral_bumblebot"
version = "0.1.0"
authors = ["porksausages <porksausages@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
regex = "1.3.7"